# Generated by Django 5.2.12 on 2026-03-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='שם התוכנה')),
                ('description', models.TextField(verbose_name='תיאור')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר')),
                ('file', models.FileField(upload_to='softwares/', verbose_name='קובץ התוכנה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
