# Generated by Django 5.2.12 on 2026-03-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='downloads',
            field=models.PositiveIntegerField(default=0, verbose_name='מספר הורדות'),
        ),
        migrations.AddField(
            model_name='software',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='דירוג (1-5)'),
        ),
    ]
