# Generated by Django 5.2.12 on 2026-03-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_software_downloads_software_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת הפוסט')),
                ('content', models.TextField(verbose_name='תוכן')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='תמונה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
