# Generated by Django 5.2.12 on 2026-03-23 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם הקטגוריה')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='license_key',
        ),
        migrations.RemoveField(
            model_name='software',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='software',
            name='rating',
        ),
        migrations.AddField(
            model_name='purchase',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='app_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='software',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares', to='store.category'),
        ),
    ]
