# Generated by Django 5.2.12 on 2026-03-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_purchase_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
