# Generated by Django 5.2.12 on 2026-03-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_siteannouncement_coupon_allows_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='software_file',
            field=models.FileField(blank=True, null=True, upload_to='softwares/', verbose_name='קובץ להורדה (Desktop)'),
        ),
    ]
